/* generated by Scade One Python Proxy 1.7.1 */

#include <stdlib.h>

#include "operator1_module0.h"
#include "operator0_module0.h"

/* module0::operator1 */
__declspec(dllexport) void* py_alloc_operator1_module0()
{
    return 0;
}
__declspec(dllexport) void py_free_operator1_module0(void *ctx)
{
    if (ctx != 0)
        free(ctx);
}

/* module0::operator0 */
__declspec(dllexport) void* py_alloc_operator0_module0()
{
    return 0;
}
__declspec(dllexport) void py_free_operator0_module0(void *ctx)
{
    if (ctx != 0)
        free(ctx);
}

/* end of file */
