@startuml 
' Arithmetic
    Expression <|-- UnaryExpr
    Expression <|-- BinaryExpr
    Expression <|-- NumericCast
    UnaryExpr <|-- PreExpr
    BinaryExpr <|-- InitialValueExpr
    BinaryExpr <|-- PreWithInitialValueExpr
    Expression -[hidden]d- NAryOperator
    note top: See [[api/language/expressions/instance.html#ansys.scadeone.core.swan.OperatorExpression OperatorExpression]]
@enduml
