@startuml
' Forward
skinparam groupInheritance 2

Forward *-- "1..*" ForwardDim
Forward *-- ForwardBody
Forward *-- "*" ForwardReturnItem
note bottom of ForwardReturnItem: See next figure

ForwardBody *-- "*" ScopeSection
ForwardBody *-- "0..1" Expression: until
ForwardBody *-- "0..1" Expression: unless

class ForwardDim {
    size: Expression (optional)
    dim_id: Identifier (optional)
    is_protected: str (optional)
}

ForwardDim *-- "*" ForwardCurrentElement
class ForwardCurrentElement {
    expr: Expression
}
ForwardCurrentElement *-- ForwardLHS

@enduml


