@startuml
' Forward return


' Accumulation
ForwardReturnItem <|-- ForwardAccuClause

class ForwardAccuClause {
    id: Identifier
    last_expr: Expression
}

' Array clause
ForwardReturnItem <|-- ForwardReturnArrayClause

class ForwardReturnArrayClause {
    id: Identifier, optional
}
ForwardReturnArrayClause *-- ForwardArrayClause
' array clause expr

ForwardArrayClause <|--- ForwardArrayClauseExpr

class ForwardArrayClauseExpr {
    expr_no_bracket: Expression
    default: Expression, optional
}
' array clause element
class ForwardArrayClauseElement {
    array_clause
}
ForwardArrayClause <|--- ForwardArrayClauseElement

ForwardArrayClauseElement::array_clause ---> ForwardArrayClause

' Protected return item
ForwardReturnItem <|-- ProtectedForwardReturnItem

@enduml
