@startuml 
' GroupTypeExpression
GroupDecl *-- GroupTypeExpression
GroupTypeExpression <|-- TypeGroupTypeExpression
GroupTypeExpression <|-- NamedGroupTypeExpression
NamedGroupTypeExpression *-- GroupTypeExpression
GroupTypeExpression <|-- GroupTypeExpressionList
GroupTypeExpressionList *-- "*" GroupTypeExpression: > positional
GroupTypeExpressionList *-- "*" NamedGroupTypeExpression: > named
@enduml