@startuml 
' Module hierarchy
Module <|-- ModuleInterface
Module <|-- ModuleBody
Module *-- "*" ModuleItem
ModuleItemDeclaration <|-- Signature
Signature <|-- Operator
ModuleItem <|-- UseDirective
ModuleItem <|-- GlobalDeclaration
note left of GlobalDeclaration
    **type**, **sensor**, **const**
and **group** declarations
end note 
@enduml
