/* generated by {{ TOOL_WRAPPER }} */

#include <stdlib.h>

#include "{{ OPERATOR_NAME }}.h"

/* {{ OPERATOR_PATH }} */
__declspec(dllexport) void* py_alloc_{{ OPERATOR_NAME }}()
{
    {% if not CONTEXT_TYPE -%}
    {% filter indent(width=4) %}
    return 0;
    {% endfilter %}
    {# #}
    {% else %}
        {% if not RESET_PARAMETERS -%}
            {% if OP_INIT -%}
            {{ INIT_NAME }}();
            {% endif %}
            {% filter indent(width=4) %}
            return 0;
            {% endfilter %}
            {# #}
        {% else %}
    outC_{{ OPERATOR_NAME }} *ctx = (outC_{{ OPERATOR_NAME }}*)malloc(sizeof(outC_{{ OPERATOR_NAME }}));
            {% if OP_INIT -%}
        {% filter indent(width=4) %}
    {{ INIT_NAME }}(ctx);
        {% endfilter %}
            {% endif %}
        {% endif %}
    return (void*)ctx;
        {# #}
    {% endif %}
}

__declspec(dllexport) void py_free_{{ OPERATOR_NAME }}(void *ctx)
{
    if (ctx != 0)
        free(ctx);
}

{% if IOS_DECLARED -%}
__declspec(dllexport) size_t py_offsets_{{ OPERATOR_NAME }}[] = {
    {% for line in IOS_DECLARED %}
    offsetof(outC_{{ OPERATOR_NAME }}, {{line}}),
    {% endfor %}
};

{% endif %}
/* end of file */