@startuml
' ActivateIf

ActivateIf *-- IfActivation

IfActivation "1" *-- "*" IfActivationBranch

IfActivationBranch  *--  "0..1" Expression
IfActivationBranch  *--  IfteBranch

IfteBranch <|-- IfteDataDef
IfteBranch <|-- IfteIfActivation

IfteIfActivation *-- IfActivation

@enduml
