@startuml
SwanItem <|-- Assertion
ScopeSection <|-- AssertionBase
AssertionBase <|-- AssertSection
AssertionBase <|-- AssumeSection
AssertionBase <|-- GuaranteeSection
AssertionBase *-- Assertion
@enduml