@startuml
' ScadeOne overview



ScadeOne "1" *-- "*" Project

note left of ScadeOne
Scade One instance
end note

note top of Project
Loaded/created [[/api/project.html Project]]'s
The Model is the owner
of the Projects
end note
Project --> "*" Project
note right on link
Project dependencies
end note

ScadeOne *-- Model
note left of Model
The [[/api/model.html Model]] object
contains the Swan
modules of the 
projects
end note

Project -left- Model

Model "1" *-- "*" ModuleBody
Model "1" *-- "*" ModuleInterface

note as ModuleNote
Module body and interface classes are
described in the [[/api/language Swan section]]
end note

ModuleBody .. ModuleNote
ModuleInterface .. ModuleNote
@enduml
