@startuml
'left to right direction
skinparam linetype ortho

enum Position
enum DirectionType
enum OrientationType

DiagramPragma *--"coordinates" Coordinates
DiagramPragma *--"size" Size
DiagramPragma *--"direction" Direction
DiagramPragma *--"orientation" Orientation
DiagramPragma *--"wire_path_info" PathInfo
DiagramPragma *--"transition_path_info" PathInfo
Coordinates *--"x" Coordinate
Coordinates *--"y" Coordinate
Coordinate *-- Position
Direction *-- DirectionType
Orientation *-- OrientationType
PathInfo *-- PathAnchor
PathInfo *-- PathPart
PathPart *-- Move
PathPart *-- PathAnchor
PathPart *-- Branches
Branches *-- PathPart


@enduml